language: objective-c
osx_image: xcode10
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
matrix:
  include:
    - osx_image: xcode10
      env: FASTLANE_LANE=code_coverage FASTLANE_ENV=default
